# Generated by Django 4.1.2 on 2022-10-30 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Karachi', 'Karachi'), ('Hyderabad', 'Hyderabad'), ('Jamshoro', 'Jamshoro'), ('Ghotki', 'Ghotki'), ('Sukkur', 'Sukkur'), ('Lahore', 'Lahore'), ('Multan', 'Multan'), ('Rahim Yar Khan', 'Rahim Yar Khan'), ('Sadiqabad', 'Sadiqabad'), ('Peshawar', 'Peshawar'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Quetta', 'Quetta'), ('Khuzdar', 'Khuzdar'), ('Naushahro Feroze', 'Naushahro Feroze'), ('Shaheed Benazirabad', 'Shaheed Benazirabad'), ('Rawalpindi', 'Rawalpindi'), ('Faisalabad', 'Faisalabad'), ('Islamabad', 'Islamabad'), ('Thatta', 'Thatta')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear')], max_length=2)),
                ('product_image', models.ImageField(upload_to='productimg')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Karachi', 'Karachi'), ('Hyderabad', 'Hyderabad'), ('Jamshoro', 'Jamshoro'), ('Ghotki', 'Ghotki'), ('Sukkur', 'Sukkur'), ('Lahore', 'Lahore'), ('Multan', 'Multan'), ('Rahim Yar Khan', 'Rahim Yar Khan'), ('Sadiqabad', 'Sadiqabad'), ('Peshawar', 'Peshawar'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Quetta', 'Quetta'), ('Khuzdar', 'Khuzdar'), ('Naushahro Feroze', 'Naushahro Feroze'), ('Shaheed Benazirabad', 'Shaheed Benazirabad'), ('Rawalpindi', 'Rawalpindi'), ('Faisalabad', 'Faisalabad'), ('Islamabad', 'Islamabad'), ('Thatta', 'Thatta')], default='Pending', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
