# Generated by Django 4.1.2 on 2022-10-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Sindh', 'Sindh'), ('Punjab', 'Punjab'), ('Balochistan', 'Balochistan'), ('Khyber Pakhtun Khawa', 'Khyber Pakhtun Khawa'), ('Azad Kashmir', 'Azad Kashmir'), ('Gilgit Baldistan', 'Gilgit Baldistan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Sindh', 'Sindh'), ('Punjab', 'Punjab'), ('Balochistan', 'Balochistan'), ('Khyber Pakhtun Khawa', 'Khyber Pakhtun Khawa'), ('Azad Kashmir', 'Azad Kashmir'), ('Gilgit Baldistan', 'Gilgit Baldistan')], default='Pending', max_length=200),
        ),
    ]
